Module2 task1
htmlacademy-vue/614941-pizza-1 pull request #2
Opened 2021-11-11 14:20 UTC by flygvardinna

2021-11-11 16:35 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                <AppDrag :transfer-data="ingredient">
drag-and-drop должен отключаться, когда достигнуто максимальное количество для ингредиента

2021-11-12 07:57 UTC, flygvardinna commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                <AppDrag :transfer-data="ingredient">
поправила

2021-11-12 16:21 UTC, Djaler requested changes
Извини, почему-то не отправил сразу остальные замечания

2021-11-12 16:21 UTC, Djaler commented on src/frontend/src/common/components/RadioButton.vue
> +      if (this.itemName === "ingredients") {
установку класса лучше сделать снаружи компонента, в конкретном месте его использования. Так как это универсальный компонент - не хорошо сюда закладывать логику, специфическую для конкретных мест

2021-11-12 16:21 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +        dough: this.findSelectedItem(this.dough),
лучше разделить этот computed на 4 отдельных. Потому что получается, например, что при смене теста, нужно заново выполнять поиск соуса, размера, ингредиентов и т.д.

2021-11-12 16:21 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      this[itemName] = items;
можно не делать копию массива и не переприсваивать потом его.
это же не глубокая копия, поэтому элементы в массиве меняются напрямую

2021-11-12 16:21 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +        ingredient.value++;
так делать не стоит. Таким образом ты неявно меняешь значение у данных, лежащих в другом месте. правильнее будет бросить событие, по которому в Index метод пойдет и увеличит значение у этого ингредиента, сам

2021-11-12 16:21 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +        return;
можно else этот не писать)

2021-11-12 16:22 UTC, Djaler commented
Я проверку закрывать не буду пока, ибо мой косяк

2021-11-13 14:54 UTC, Djaler commented
Ну или давай так - я сейчас на доработку отправлю (а то другие заявки принимать не могу), но можешь мне ещё раз дать это задание на проверку (не через интерфейс академии, просто напиши тут)

2021-11-13 18:12 UTC, flygvardinna commented
Окей, спасибо! А то я удивилась, неужели так мало замечаний в первый раз) я думаю, что в понедельник-вторник все поправлю и напишу тебе

2021-11-19 17:43 UTC, flygvardinna commented
@Djaler Привет! Поправила замечания, погляди, пожалуйста, как будет время

2021-11-19 18:00 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +        ingredient.value++;
проблема осталась та же. ты меняешь значение в ingredient по ссылке напрямую. Проверь, убери вот этот вызов `this.changeIngredientValue`, код продолжит работать. Это не правильно, поскольку неявно. Так как тебе нужно просто передать в `this.changeIngredientValue` имя ингредиента и новое значение - сделай `this.changeIngredientValue({ name: ingredient.name, value: ingredient.value + 1 })`

2021-11-19 18:01 UTC, Djaler commented
А с остальным все хорошо

2021-11-19 18:46 UTC, flygvardinna commented on src/frontend/src/views/Index.vue
> +        ingredient.value++;
Спасибо, поняла)

2021-11-19 18:47 UTC, merged